### PR TITLE
Adding example diesel r2d2

### PR DESCRIPTION
**Pull request by manuelarte**
I saw an example of how to use postgresm-embedded with axum, and I thought it could be a good idea to add an exmple on how to use it with diesel+r2d2

### CODE REVIEW

**Comment by brianheineman** [comment]
@manuelarte thank you for the PR!  Would you mind updating the example so that is retrieves some data from the database using Diesel to illustrate that it is working?

**Comment by manuelarte** [comment]
> @manuelarte thank you for the PR! Would you mind updating the example so that it retrieves some data from the database using Diesel to illustrate that the connection/pool is working? Thanks!

Hi @brianheineman ,

I added an example of creating a post following: https://diesel.rs/guides/getting-started

**Comment by brianheineman** [comment]
Thanks for the contribution @manuelarte!

**Comment by manuelarte** [comment]
My pleasure

**Pull request merged**
